### ISSUE TITLE
Cohort Characterization generation causes other cohort characterizations screens to hang

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1136] opened 2018-11-16 17:58 UTC
## Steps to reproduce behavior
1) go into characterizations
2) generate a characterization
3) wait a minute - then go open another window and go into characterizations
4) opening screen hangs

**Comment by fdefalco** [comment] 2018-11-20 15:00
Appears to be hanging waiting on the following request:

https://epi.jnj.com:8443/WebAPI/cohort-characterization?size=10000

**Comment by chrisknoll** [comment] 2018-11-20 17:20
Reported in WebAPI: OHDSI/WebAPI#700

**Comment by anthonysena** [comment] 2019-02-11 19:55
Currently unable to reproduce this on the latest code base and will close this out since we can continue to track this under OHDSI/WebAPI#700.

**Closed by anthonysena** 2019-02-11 19:55 UTC
Labels: bug, cohort characterization
