### ISSUE TITLE
Author isn't displayed for IR

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/Atlas#1732] opened 2019-05-20 09:31 UTC
### Expected behavior
Author is shown
### Actual behavior
Author column is empty
### Steps to reproduce behavior
Create and save new Incidence Rate

**Comment by pavgra** [comment] 2019-05-22 15:11
Duplicate of https://github.com/OHDSI/Atlas/issues/1737

**Closed by pavgra** 2019-05-22 15:11 UTC
