### ISSUE TITLE
CC results filter to prevalence percent not working

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#2509] opened 2021-04-13 18:30 UTC
### Expected behavior

As described in #1982, the CC results can be filtered to only covariates with prevalence greater than a percent you specify.

### Actual behavior

Nothing happens

### Steps to reproduce behavior

I tried this in our version and in the demo site, both v2.8.1. Go to a completed cohort characterization, try to change the percent filter at the top right, and hit apply. A post back occurs, but then the results are unfiltered.

**Comment by anthonysena** [comment] 2023-12-19 14:47
Tested this on v2.12.1 and unable to reproduce this issue so closing it out.

**Closed by anthonysena** 2023-12-19 14:47 UTC
Labels: bug, cohort characterization
