### ISSUE TITLE
Vertical Scrollbar not enabled in new Atlas Cohort Definition

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#159] opened 2016-06-17 13:30 UTC
The vertical scrollbar in Cohort Definition screens is not enabled. Only content within the initial screen resolution are viewable.

**Comment by chrisknoll** [comment] 2016-06-20 20:46
Steps to reproduce:
1. Open Cohort Definition that does not have cohort results generated
2. Navigate to Patient Profiles tab
3. Notice dialog is already opened saying there are no people to show
4. Close dialog by clicking hard-to-see X in the topbar.
5. Scrollbars will reappear.

The problem is the patient profile tab is opening up a hidden dialog window (which is contained inside the patient profile tab? so not exactly a dialog) but this behavior is causing the bootstrap css to think a modal is open, and it applies the modal-open css to the html body thus making the scrollbars disappear.

Could the message in the Patient Profile simply say in a DIV element that there are no patients to show instead of a dialog?

**Comment by Sigfried** [comment] 2016-06-21 14:27
Thanks for figuring it all out, Chris!

The problem was already not occurring on the recent version of the profile branch. The master branch has very different code in profile-manager at this point, so I fixed it there. When the current profile branch gets merged in we need to ignore any changes to the profile-manager files on master.

**Closed** 2016-06-21 14:27 UTC
