### ISSUE TITLE
Cohort generate with feature - add cohort period

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#658] opened 2018-04-23 03:07 UTC
### Expected behavior
Be able to generate features for cohort-period. ie between cohort-start-date and cohort-end-date including both dates.

**Add** 
Cohort Period: between cohort start date and cohort end date including both dates.

**Already exists:**
Long Term: 365 day lookback. 
Short Term: 30d lookback. 
Overlapping: Event spans cohort start date.

### Actual behavior
Only able to generate cohort characteristics for before cohort start date with long-term, short-term or overlapping periods.

**Comment by anthonysena** [comment] 2019-07-02 20:32
Closing - duplicate of #623.

**Closed by anthonysena** 2019-07-02 20:32 UTC
Labels: cohort, enhancement
