### ISSUE TITLE
navigating away from new cohort definition gets lost

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Atlas#160] opened 2016-06-17 15:00 UTC
I started defining a new cohort. I needed to add or find some concept sets and navigated to that page. Then if I tried to look at a specific concept set or use the back button to get back to cohort definition, I got alert prompt: "Cohort changes are not saved. Would you like to continue?" I could navigate back to the cohort definition list, but my new cohort wasn't there (it hadn't been saved yet). I could find no way to actually save the work I had done so far in defining the cohort (not much), so had to abandon changes and start over.

**Comment by chrisknoll** [comment] 2016-06-17 22:24
So would you say being able to open a cohort and concept set at the same time would be useful here?

**Comment by fdefalco** [comment] 2016-06-18 15:05
This is an issue with not creating the current cohort definition context that would provide the backlink he needs to get back to the cohort definition.  I believe we currently only create it once the cohort definition has been saved but we should create it as soon as any changes are made on the cohort definition editor screen thereby enabling the back link to appear.

**Comment by chrisknoll** [comment] 2016-06-18 16:12
@Sigfried , is this the steps you're performing in the app:
1. New Chort Definition
2. Make some changes (add criteria, add concept sets)
3. You want to look at a concept set so you click on concept sets, anc choose one (this will result in an alert that you have unsaved changes)
4. You can't navigate back to the cohort definition because the cohort definition context is lost.

Is that what's happening? I'm doing the above steps on ohdsi.org/web/atlas to understand what you might be seeing. Could you please add the steps to reproduce the behavior that you are seeing?

**Comment by chrisknoll** [comment] 2016-06-18 16:14
@fdefalco , I am trying to reproduce the 'not creating the back link' but when I click 'new definition' a link to the cohort immediately appears in the left nav titled 'New Cohort Definition'.  Are you seeing this differently on one of the branches?

**Comment by fdefalco** [comment] 2016-06-19 15:35
Ah yes - that was an issue in one of my working branches - @Sigfried - where are you seeing it?

**Comment by Sigfried** [comment] 2016-06-20 13:49
(Sorry for the delay.) Here's what I did, which I now realize was based on not seeing how to find a concept. This is on the master branch of ATLAS.

Go to cohort page.
Click New Cohort.
Add a primary event filter (Drug).
Click the green Add button next to "a drug exposure of".
Fail to notice "Local" in the Select Concept Set dropdown (maybe it wasn't there? but it is now.)
Wonder how to select an existing concept set.
Hit escape to remove the Select Concept Set dialog.
Go to Concept Sets tab. Nothing is there.
Go to Concept Sets on left menu.
Weird -- now I see concept sets, but Friday I didn't.
More weird, the back button works fine now, but Friday it didn't.

So I have no way to replicate my problem right now. On Friday I was actually on my new local cartoon branch, but I branched that off of master, I believe (definitely from commit 442af7e66adcddbbcbc8d0bdbdbb04711f28d502). And testing now, cartoon and master behave identically. I'm wondering if my selecting Local in the Select Concept Set earlier this morning loaded concept sets somewhere so I can't replicate the issue anymore.

**Comment by chrisknoll** [comment] 2016-06-20 14:47
Thanks @Sigfried , one thing I'm missing from your above steps compared to your description from your original post is that you said you "Tried to look at a specific concept set".  At step 8 (go to concept sets tab) it makes sense you see nothing there because there are no concept sets int he cohort definition yet (it's a new cohort).  Then you click concept sets on the left nav, which (not-so-wierdly) you see concept sets, but these are concept sets from the repository.  If you selected a concept set from this list to look at it, you would have gotten an unsaved changes alert, and if you just continued through it, it would have shown you the concept set you selected, but lost your context to your cohort definition.

Do you see any problems with not being able to open a concept set from he repository while having a cohort definition open for editing?

**Comment by Sigfried** [comment] 2016-06-21 10:02
I don't know. I find the way it's currently working to be confusing, but I don't feel like I have a clear enough sense of what's going on to have an opinion on how it should work.

**Comment by anthonysena** [comment] 2016-08-12 20:47
Closing this with a note to include some overview of cohort concept sets versus repository concept sets in the user documentation (#147).

**Closed by anthonysena** 2016-08-12 20:47 UTC
