### ISSUE TITLE
Public Atlas site reports: application initialization failed, unable to connect to an instance of the webapi.

### ISSUE THREAD

**Issue by gscottgordon** [OHDSI/Atlas#616] opened 2018-03-27 13:40 UTC
### Actual behavior
When attempting to utilize the public Atlas portal (http://www.ohdsi.org/web/atlas/), after passing through Atlas animation, console appears but with an error message:

"application initialization failed
unable to connect to an instance of the webapi.
please contact your administrator to resolve this issue."

**Comment by leeevans** [comment] 2018-03-27 14:04
@gscottgordon there were some updates made to the OHDSI atlas site over the weekend.
I'm not currently seeing that error when I browse to the site.

Could you try closing your browser and clearing the browser cache to see if that corrects the issue?

**Comment by gscottgordon** [comment] 2018-03-29 14:07
Hmm… You’re right – when I log in from a home PC it works.   I cleared caches on all my work PC browsers with no luck.  I’ll troubleshoot - it may be something to do with my work VPN, although it worked fine the times I accessed it in the past.


------
Gideon Scott Gordon, Ph.D.
Senior Health Informatics Officer
FDA/CDER/OSP
240-402-8560

**Comment by chrisknoll** [comment] 2018-03-29 14:38
I had this exact problem using my VPN...I disconnected my VPN (we use Junos Pulse, so I went into the app, disconnected, and reconnected) and then the site came up properly.

@gscottgordon : if you open up your chrome console (ctrl-shift-i) and then refresh Atlas on the PCs with the issue: do you notice that the load times are very slow (like 5 seconds between requets) like this:

![ohds_atlas_vpn](https://user-images.githubusercontent.com/6818777/38094901-1b9019e0-333d-11e8-88c8-6e316aea6e51.png)

This is what it should look like normally (which I ran it on my home PC, separate from my work laptop with VPN):
![ohds_atlas_home](https://user-images.githubusercontent.com/6818777/38094975-429e4a52-333d-11e8-87f9-9a3e5f6fa8cf.png)

**Comment by gscottgordon** [comment] 2018-03-29 15:16
I will check when I'm back home so I can switch my VPN off and see if I have the same effect.   It is a new problem though. 

I don't see an abnormal delay.  But I do get the following errors:

![image](https://user-images.githubusercontent.com/37839107/38097131-8b7b790c-3342-11e8-8f89-849fde378cc9.png)

**Comment by chrisknoll** [comment] 2018-03-29 15:44
Could be a temporary outage (if you're getting a 503, then you got connectivity to the server, just had an error.  The Origin messages is a bit of a red herring:  because the first request OPTIONS failed, the subsequent checks are reporting errors.  The real issue was the 503 Service Unavailable in the initial request.

Could you try again? I just confirmed on my side that the website is online...

**Comment by anthonysena** [comment] 2018-04-10 19:33
@gscottgordon - I'm going to close this out as it appears to be a temporary outage. If you are still experiencing issues, please re-open this issue. Thanks!

**Closed by anthonysena** 2018-04-10 19:33 UTC
