### ISSUE TITLE
Lingering Concept Sets and Warnings when creating cohorts via copy

### ISSUE THREAD

**Issue by AnthonyMolinaro** [OHDSI/Atlas#984] opened 2018-10-05 15:19 UTC
### Expected behavior
Once a concept set is removed from a cohort definition, it should no longer be seen in the Concept Sets tab and there should be no further Warnings about it.

### Actual behavior
When creating cohorts via copy, the Concept Sets tab shows old concept sets even though they've been removed.  I created cohort 5338 by copying 5336 and then proceeded to remove the concept set in the initial event section.  However, even after saving and generating, 5338 still shows the original concept set in the Concept Sets tab and the Warning claims that the old concept set is not being used.

### Steps to reproduce behavior
1. Create a cohort as a copy of another cohort.
2. Replace the initial event concept set with another.
3. Save and generate.
4. Concept Sets tab and Warning tab will still refer to the removed concept set.

![screenshot 4](https://user-images.githubusercontent.com/31700317/46542958-be182f00-c88d-11e8-8afa-a64ff4beb30c.png)

![screenshot 5](https://user-images.githubusercontent.com/31700317/46542975-c40e1000-c88d-11e8-9b25-5486787d324b.png)

**Comment by chrisknoll** [comment] 2018-10-05 16:40
This may indicate an out-of-sync issue (which is bad) with the underlying cohort definition's concept set and the concept set that the concept set tab is presenting. These concept sets should be the same reference to the cohort definition's conceptSetList.

**Comment by anthonysena** [comment] 2019-07-02 20:58
Relating this to #1933

**Comment by pbr6cornell** [comment] 2019-07-14 01:23
It would be very useful to get the Warnings tab bug-free as part of ATLAS 2.8, because that'll allow us to remove unused conceptsets.

**Comment by anthonysena** [comment] 2019-09-23 19:43
Closing this out since I'm unable to reproduce this on the 2.7.4 release candidate for ATLAS.

**Closed by anthonysena** 2019-09-23 19:43 UTC
Labels: bug, cohort
