### ISSUE TITLE
tooltips are not closed when changing report type

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/Atlas#1586] opened 2019-03-22 11:22 UTC
For data sources

### Expected behavior
Tooltip is closed when the type of report is changed

### Actual behavior
Tooltip is still shown

### Steps to reproduce behavior
1. Select report type with treemap
2. Try to select another report type in drop down menu
3. After click on new report type the tooltip appears if the mouse is located on the treemap
4. After the report type changes the tooltip is still visible

**Comment by pavgra** [comment] 2019-03-27 11:26
Duplicate of https://github.com/OHDSI/Atlas/issues/1477

**Closed by pavgra** 2019-03-27 11:26 UTC
