### ISSUE TITLE
Data Sources / Death report:  toggling between sources produces error

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1287] opened 2019-01-31 20:42 UTC
### Expected behavior

On Data Sources / Death report:  when on a report for a given database, switching to a different database should refresh the report without error.

### Actual behavior

![image](https://user-images.githubusercontent.com/731930/52083829-89339480-256e-11e9-8e13-7939b7779ff7.png)

### Steps to reproduce behavior

On Data Sources / Death report:  Selected first database.  Then switched to different database in list.

**Comment by YangDaeIl** [comment] 2019-02-07 01:08
I am also waiting for an answer.

**Comment by pavgra** [comment] 2019-02-14 14:31
@anthonysena , could you try to reproduce the issue with the latest codebase? We were not able to catch the issue

**Comment by anthonysena** [comment] 2019-02-19 20:34
@pbr6cornell I'm unable to reproduce this on the latest code base in our beta environment so I'm going to close this out. Thanks!

**Closed by anthonysena** 2019-02-19 20:34 UTC
Labels: bug, data sources
