### ISSUE TITLE
Incidence Rates: new analysis has emty updated field

### ISSUE THREAD

**Issue by wivern** [OHDSI/Atlas#1800] opened 2019-05-30 09:42 UTC
### Expected behavior
Newly created analysis is on the top of analyses list.

### Actual behavior
Newly created analysis is on the end of analyses list.

### Steps to reproduce behavior
- Create new Incidence rate, give name to it
- Press save and close analysis

`updated` field used to sort items by default, but when you create new analysis the `updated` field becomes empty and this is the reason why new analysis goes to the end of list.
If there are many analyses in the list you might be confused and decide analysis was not saved.

![2efc0dd2-a6eb-4b98-804c-d1c8af72cc63](https://user-images.githubusercontent.com/1109753/58624148-44c7c380-82d8-11e9-9eaa-cd3933a78fa9.png)

**Comment by chrisknoll** [comment] 2019-05-30 12:56
Just some background, I think it was by design that the created date gets set on creation, the updated date gets set on update, allowing you to distinguish when something was created vs updated.  I can understand the problem, tho, with the null value in the updated date.

Suggestion to resolve:
1. Set the updated date on creation.
2. Migration script will copy the created date into the updated date for all `updated_date is null` rows.

**Comment by pavgra** [comment] 2019-05-30 14:14
> Suggestion to resolve

Why would you need to change data if we can just apply `COALESCE(updated_at, created_at` logic at UI when sorting by the column?

**Comment by anthonysena** [comment] 2019-07-03 18:05
Looks like we fixed this in 2.7.2. Closing it out.

**Closed by anthonysena** 2019-07-03 18:05 UTC
Labels: bug, ir calc
