### ISSUE TITLE
Generate button on characterization execution page doesn't show generating 

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1128] opened 2018-11-16 16:38 UTC
### Expected behavior
When generating multiple characterizations for several databases the generate button will show for those datasources generating with moving circle
### Actual behavior
When generating multiple characterizations for several databases the generate button doesn't show for all datasources generating with moving circle
### Steps to reproduce behavior
For a given characterization click generate for 4 databases, watch generate button, some do not change

**Comment by johnSamilin** [comment] 2019-01-15 13:32
@jhardin29 unfortunately, I couldn't reproduce it

**Comment by anthonysena** [comment] 2019-01-15 19:58
@johnSamilin - I'm able to reproduce this in our environment. I left the developer console open to see if any errors are thrown and unfortunately nothing is erroring out nor is the screen updating. What is problematic here, beyond the UI response, is the fact that a user is able to kick of > 1 job on a single data source. This is causing some operational issues in our environment.

What I noticed is that the first two jobs kicked off without issue. The 3rd job exhibits the problem that @jhardin29 mentioned. It is also the case that the first two jobs that successfully started were at the top of the list (sources 3 and 5 of 15) and the one that had the issue was towards the bottom (13 of 15).

**Comment by anthonysena** [comment] 2019-01-15 21:42
One more update - there appears to be some async behavior here. I left the page open a while and eventually the button changes from "generate" to "generating" for the source that was taking a while. Also worth noting, I'm performing this test against the v2.6.0 tag (for Atlas & WebAPI)

**Comment by johnSamilin** [comment] 2019-01-21 11:35
@anthonysena I pushed a fix for this behaviour: there was an improper use of the observable

**Closed** 2019-01-23 13:39 UTC
Labels: bug, cohort characterization
