### ISSUE TITLE
Data Sources / Procedure report - exporting data via CSV generates console errors

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1283] opened 2019-01-31 19:03 UTC
### Expected behavior

On Data Sources / Procedure Occurrence report, On the Prevalence Table, when clicking 'CSV' button, a file is generated which exports the content into a csv file.

### Actual behavior

The csv file is produced, but a large number of console errors were produced at same time.  The resulting file appears to have valid content.

![image](https://user-images.githubusercontent.com/731930/52077894-10c5d700-2560-11e9-87d4-05b9aa38b465.png)

### Steps to reproduce behavior

Go to Data Sources / Procedure Occurrence report / ,Prevalence Table, click 'CSV' with Google Developer console open.

**Comment by anthonysena** [comment] 2019-02-11 22:06
In reviewing this issue, the errors noted in the console are coming from the d3.js library so I suspect that a drill down report was open that was producing the errors and the CSV export either caused the screen to redraw and throw the same errors again. I'm unable to reproduce the error when exporting to CSV when the drill down report is **not** active.

**Comment by johnSamilin** [comment] 2019-02-18 12:35
I guess this issue should have been fixed by this PR: https://github.com/OHDSI/Atlas/pull/1263
@pbr6cornell could you try to reproduce it with the latest master branch?

**Comment by anthonysena** [comment] 2019-02-19 20:34
@pbr6cornell I'm also unable to reproduce this on the latest code so I'm going to close this out. Thanks!

**Closed by anthonysena** 2019-02-19 20:34 UTC
Labels: bug, data sources
