### ISSUE TITLE
Counts not visible in inclusion report in ATLAS

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#2632] opened 2021-10-29 15:38 UTC
### Expected behavior
When a cohort completes and shows numbers of subjects in the UI when the user clicks on the View Reports button it should display the report with the proper counts.
### Actual behavior
When a cohort completes and shows numbers of subjects in the UI when the user clicks on the View Reports button it does not display the report with the proper counts and instead shows 0 counts.
### Steps to reproduce behavior
see this image: 
![image](https://user-images.githubusercontent.com/11822115/139463107-d299346b-bb9e-4576-b891-172eecc7d723.png)

**Comment by anthonysena** [comment] 2022-05-03 20:57
I'm unable to reproduce this on v2.11 so I'm going to close it out. @jhardin29 if this problem persists, please re-open and we'll investigate.

**Closed by anthonysena** 2022-05-03 20:57 UTC
