### ISSUE TITLE
Make the process of cohort importing clearer

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2414] opened 2020-12-17 09:02 UTC
Now to import cohort we have to:
1)New cohort -> Choose the **EXPORT** tab
2)Select the JSON tab
3)Insert the imported JSON
4)Click "reload"

**Comment by chrisknoll** [comment] 2020-12-20 12:53
Just to be clear: the cohort import works such that if you have an existing cohort definition open, importing will overwrite just the expression.  I believe in other areas, when you do an import function, it seems to create a new entity.  So we need to get the semantics straight.  In addition the import on cohort defintiion just imports a new expression, it doesn't deal with importing the name, etc, because the import was designed to just load a new expression, not overwrite the entire definition.

So, when looking at the 'import' function, let's be clear about what it should do and then make it work consistent (and I'm not sure the other places like cohort characterization, etc are working 'correctly').

It may be nice to have a 'new from import' option when creating a new entity (like new cohort, new pathway, etc) where a person can paste JSON for the new entity) but once inside an existing entity, import shouldn't create a new entity, it should just overwrite the existing one with the new design.

**Comment by vojtechhuser** [comment] 2021-01-08 16:15
I agree that user is often surprised if import results in new element or overwrite of current element

**Comment by anthonysena** [comment] 2022-05-03 21:51
Closing in favor of #2630 which aims to clear up the confusion with this functionality.

**Closed by anthonysena** 2022-05-03 21:51 UTC
Labels: enhancement, cohort
