### ISSUE TITLE
[ATLAS 2.7 TEST] RC / DRC on Concept Set Compare Tab Not Displying

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#1537] opened 2019-03-15 21:10 UTC
### Expected behavior
RC / DRC columns are populated on Concept Set Compare tab

### Actual behavior
RC / DRC columns are empty

![image](https://user-images.githubusercontent.com/6305439/54461961-81a60480-4744-11e9-8415-bce864295d35.png)

### Steps to reproduce behavior

1. Concept Sets --> search for 7364
2. Select Concept Set 7364 to open it
3. Go to "Compare" tab
4. Open "Concept Set 2"
5. Search for 6314 and select it
6. "Compare Concept Sets" button
7. Sort the RC column and you'll see some have no data (under data source JNJ Network) - maybe this is a problem with that data source needing to be updated?

I also tried to change to IBM CCAE V870 but it got stuck - but that could be our DB trying to take a nap.
![image](https://user-images.githubusercontent.com/6305439/54462180-33453580-4745-11e9-94b3-ee17dab66542.png)

**Comment by anthonysena** [comment] 2019-04-05 14:09
@ericaVoss - looking into this issue in our environment, I'm able to reproduce the issue. This only seems to happen for our JNJ_NETWORK data source - it appears that it may need a refresh. I'm able to load up the record counts for the other data sources is our environment and I do not see any missing record counts for those. I'm going to close this out since it appears to be specific to that J&J source. If you see further problems here, please re-open this issue and we can look into it. Thanks!

**Closed by anthonysena** 2019-04-05 14:09 UTC
Labels: bug, vocab/conceptset
