### ISSUE TITLE
Replace a Concept Set with Another

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#362] opened 2017-02-24 22:25 UTC
This is an enhancement request not an issue.

Right now a concept set in a cohort can only be changed or deleted.  I would love if there was an option to swap it out for another.

Often I will have another more appropriate concept set developed to replaced one already in use.  A concept set can be used in many places in one cohort.  So doing a swap would be awesome.

**Comment by anthonysena** [comment] 2017-07-20 18:06
Closing since it is a dupe of #365

**Closed by anthonysena** 2017-07-20 18:06 UTC
Labels: cohort, enhancement
