### ISSUE TITLE
Switching between tabs in IR, the Generations is often not populated

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#2045] opened 2019-09-24 13:37 UTC
### Expected behavior

When switching to Generations tab in IR, the data sources and generated statistics should be shown

### Actual behavior

Switching between tabs in IR, the Generations is often not populated

![image](https://user-images.githubusercontent.com/26966141/65516291-c3abc200-deae-11e9-9131-37bb05cd9e54.png)

![image](https://user-images.githubusercontent.com/26966141/65516315-cefeed80-deae-11e9-9357-817151cb2c4c.png)

Propose to fix in 2.8

**Comment by anthonysena** [comment] 2019-09-24 13:50
@gklebanov I'm unable to reproduce this in our environment with security disabled. @pavgra can you re-create this bug with security enabled?

**Comment by anthonysena** [comment] 2020-04-27 12:37
Closing since I'm unable to recreate this behavior.

**Closed by anthonysena** 2020-04-27 12:37 UTC
Labels: bug
