### ISSUE TITLE
Missing vocabulary 

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Atlas#524] opened 2018-01-11 23:58 UTC
Expected behavior
When using the Advanced Option of Atlas, I expect to be able to select the ABMS vocabulary.

Actual behavior
When using the Advanced Option of Atlas, the ABMS vocabulary is not one of the listed Vocabularies.

Steps to reproduce behavior
Open Atlas. Click the "Advanced Options", look and not find the ABMS vocabulary.

**Comment by anthonysena** [comment] 2018-04-10 20:01
Hi @MelaniePhilofsky - sorry for the delay here. The vocabularies that are displayed under the "Advanced Option" of the vocabulary search are sourced from the default vocabulary provider data source. So, ABMS will be displayed if that vocabulary was part of the vocabulary download taken from Athena. In our environment, I can confirm that we have downloaded the ABMS terminology and it is displayed under the list of vocabularies. I'm going to close this out since it doesn't appear to be a bug but if there are other environmental questions related to this item, please re-open and we can continue the discussion. Thanks!

**Closed by anthonysena** 2018-04-10 20:01 UTC
Labels: question, vocab/conceptset
