### ISSUE TITLE
Priority method is calling twice if we refresh configuration page

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2103] opened 2020-01-22 09:18 UTC
![image](https://user-images.githubusercontent.com/56290675/72881067-1d16e700-3d11-11ea-8712-ba918f1732c8.png)
### Steps to reproduce behavior
1)open #/configure page
2)refresh the page

**Comment by olga-ganina** [comment] 2020-01-27 13:09
Closing this one as it is duplicate of https://github.com/OHDSI/WebAPI/issues/1429

**Closed by olga-ganina** 2020-01-27 13:09 UTC
Labels: bug
