### ISSUE TITLE
Initialization failed when cacheSources is turned on

### ISSUE THREAD

**Issue by wivern** [OHDSI/Atlas#2138] opened 2020-03-02 12:17 UTC
### Expected behavior
Application initialized without errors

### Actual behavior
Got the following error:
```
Cannot read property 'Vocabulary' of undefined
    at Object.setSharedStateSources (SourceAPI.js:94)
    at Application.js:272
    at new Promise (<anonymous>)
    at Application.initServiceInformation (Application.js:265)
    at Application.synchronize (Application.js:135)
    at main.js:53
```

### Steps to reproduce behavior

1. Turn on `cacheSources=true;` in the configuration
1. Reload application twice, the second and following attempts raises an error

**Comment by ssuvorov-fls** [comment] 2020-07-31 05:38
Can't reproduce
Seems to be fixed by other issues

**Closed** 2020-07-31 05:37 UTC
Labels: July14-July27, June16-June30, June2-Jun15
