### ISSUE TITLE
Shiro sign-in - access, whom to contact

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#443] opened 2017-08-23 00:07 UTC
### Expected behavior
> For more information on how to get access please contact the system administrator.

![image](https://user-images.githubusercontent.com/13936600/29592978-7ef419ba-8775-11e7-95f5-4ed1fa645cc4.png)

### Actual behavior

> For more information on how to get access please contact the Ajit Londhe, Erica Voss and/or Anthony Sena.

![image](https://user-images.githubusercontent.com/13936600/29592955-3946518a-8775-11e7-986a-793212216683.png)

**Comment by fdefalco** [comment] 2017-08-23 01:05
Working as intended.  (just kidding of course)

**Comment by gowthamrao** [comment] 2017-08-23 01:29
lol! we know you guys and are grateful!!

**Comment by ericaVoss** [comment] 2017-08-25 12:30
Hey, what is this!  :)

**Comment by anthonysena** [comment] 2017-08-29 15:28
As I was working through #442, I had made this change since I figured @gowthamrao would eventually find this page. :-)

We'll close this out once #442 is approved and merged....

**Closed** 2017-08-29 19:12 UTC
