### ISSUE TITLE
[ATLAS 2.7 TEST] Data Sources: Cascading NA's appearing in Multiple Reports

### ISSUE THREAD

**Issue by AnthonyMolinaro** [OHDSI/Atlas#1522] opened 2019-03-15 17:02 UTC
### Expected behavior
Treemap procedure report should show a report similar to the following (using measurement as an example):

![image](https://user-images.githubusercontent.com/31700317/54448460-32e77300-4722-11e9-9587-704fb92c9734.png)

### Actual behavior
However, for procedure, we see 3 NA's at the top of the image when scrolling over the treemap
![image](https://user-images.githubusercontent.com/31700317/54448181-7f7e7e80-4721-11e9-801e-9b23102e0e22.png)

### Steps to reproduce behavior

1.From Atlas home choose data sources.
2. Choose a db and the procedure report.

This is also occurring in the following reports: condition_era, drug_era, and observation.

**Comment by chrisknoll** [comment] 2019-03-15 17:38
This could be considered a bug, but this NA value occurs when the concept_hierarchy doesn't provide a rollup for the given concept in the report. So, this could happen on procedures, drugs, etc, anywhere we try to do a rollup (which is what the tree map is showing).  

The fix would have to be found somewhere on the WebAPI/reporting side where every concept is guaranteed to roll up to a level 1-level 2 - level 3 hierarchy.

It is interesting that this appears on drug_era, since all concepts in there are ingredient, and all ingredients should roll up to some atc 1/3/5 class.  But still a bug non-the-less.

**Comment by anthonysena** [comment] 2019-04-03 18:18
Looking at the screenshot from @AnthonyMolinaro, this looks like the procedure report has concepts which do not roll up through the concept hierarchy used in the Achilles analyses. In the case of procedures, these are rolled up through SNOMED. So, I'd say this is a limitation of our ability to group some of these clinical concepts to higher order classifications via the vocabulary and not a bug in ATLAS. 

I'm going to close this one out since I'd argue this isn't a bug that should be addressed in ATLAS but potentially an enhancement to the `concept_hierarchy` table construction in WebAPI.

**Closed by anthonysena** 2019-04-03 18:18 UTC
Labels: bug, data sources
