### ISSUE TITLE
Need better and consistent time formatting on job screens

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#1991] opened 2019-07-30 19:17 UTC
### Expected behavior
The tool would show elapsed execution time in hours:minutes:seconds or even days:hours:minutes:seconds 

### Actual behavior
it displays everything in minutes:seconds or other formats on different screens
![image](https://user-images.githubusercontent.com/26966141/62158179-df468200-b2dc-11e9-9a05-1b0a6db90a4b.png)

Considering how simple that fix should be (simple formatting) - I propose to fix it in 2.8 but will let Patrick to make a decision

**Comment by anthonysena** [comment] 2019-11-21 21:23
Closing since it is duplicate of #2034.

**Closed by anthonysena** 2019-11-21 21:23 UTC
