### ISSUE TITLE
Cohort Pathways path detail location

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#1545] opened 2019-03-16 01:05 UTC
### Expected behavior
The path details window always shows up below the sunburst plot

### Actual behavior
Occasionally the path details window will show up to the right of the sunburst plot

### Steps to reproduce behavior
Click through the different pathway options

**Comment by anthonysena** [comment] 2019-04-05 13:52
@clairblacketer - was there a specific pathways analysis that you ran in our environment that exhibited this behavior? I'm having trouble reproducing the issue at the moment.

**Comment by anthonysena** [comment] 2019-07-03 18:19
@clairblacketer - I'm going to close this out as I'm not able to reproduce this. Thanks!

**Closed by anthonysena** 2019-07-03 18:19 UTC
Labels: Pathways, bug
