### ISSUE TITLE
name of concept set is hard to type (is backwards)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#411] opened 2017-06-20 20:50 UTC
### Expected behavior
concept set name can be typed nicely
### Actual behavior
name is "backwards" (has to be spelled starting from end)
not user friendly

### Steps to reproduce behavior
create new cohort and concept set and name it 'backwards'. The name taken will be not what you typed. see pic below.

![image](https://user-images.githubusercontent.com/7526119/27355255-59e4adc0-55d8-11e7-8da8-347c43d3b95b.png)

**Comment by chrisknoll** [comment] 2017-06-20 22:14
Dupe of #395 . This is fixed on master.

**Closed by chrisknoll** 2017-06-20 22:14 UTC
