### ISSUE TITLE
some content is displayed on secured pages

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#2020] opened 2019-08-27 20:29 UTC
### Expected behavior
When trying to access secured page without required access right, the page should not display any content except for the page title and "You do not have access to this feature. For more information on how to get access please contact the System Administrator". 

### Actual behavior
In multiple pages, instead of just showing "access denied", some other page elements are being displayed. In some, "access denied" message is completely missing 

search screen
![image](https://user-images.githubusercontent.com/26966141/63805280-18c3da80-c8e7-11e9-8a9a-7bed60436222.png)
search and import tabs should not be there

concept sets screen
![image](https://user-images.githubusercontent.com/26966141/63805224-f5992b00-c8e6-11e9-98a7-d29ccf22b54c.png)

characterization
![image](https://user-images.githubusercontent.com/26966141/63805361-401aa780-c8e7-11e9-9fdc-2c4464646715.png)
remove tabs and buttons

![image](https://user-images.githubusercontent.com/26966141/63805419-63455700-c8e7-11e9-95e8-568c6eab9d7f.png)
make sure message is consistent with an alignment on other pages

Also, would be nice to be able to provide a link/email for the "System Administrator"

I reported all these before but somehow it is not addressed - I looked at existing issues and didn't find this issue captured. So, I am tagging it for 2.8 - considering it is a bug and low effort required to fix it. But assigning to Patrick to confirm he is OK with that being in 2.8 release.

**Comment by olga-ganina** [comment] 2020-01-13 16:10
@anthonysena we cannot reproduce it on 2.7.5, can you please double check so we can close it?

**Closed** 2020-04-27 12:45 UTC
Labels: bug
