### ISSUE TITLE
Characterization - explore under concept seems to hang

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1428] opened 2019-03-07 01:58 UTC
### Expected behavior

Clicking hyperlink beneath a covariate name should pop up window that populates with vocabulary lineage for covariate prevalence.

### Actual behavior

Clicking the 'explore' hyperlink does pop open textbox, but seems to hang, not returning any results after many minutes.  Chrome shows load resource error that may be related, in screenshot:

![image](https://user-images.githubusercontent.com/731930/53926721-93a3eb00-4052-11e9-9f9c-19e736ac2b61.png)

### Steps to reproduce behavior

Click explore hyperlink under any covariate in Condition table.

**Comment by pavgra** [comment] 2019-03-07 02:21
The same design as in https://github.com/OHDSI/Atlas/issues/1427#issuecomment-470352469

**Comment by anthonysena** [comment] 2019-03-08 03:43
@pbr6cornell I'm unable to reproduce this in our beta environment currently so I'm wondering if maybe there was a back end problem retrieving results from the appliance?

**Comment by anthonysena** [comment] 2019-03-08 19:29
Closing since we're unable to reproduce and it may have been a temporary problem on our db server. I will re-open if this persists.

**Closed by anthonysena** 2019-03-08 19:29 UTC
Labels: bug, cohort characterization
