### ISSUE TITLE
Cannot generate or save features to an existing characterization

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1284] opened 2019-01-31 19:31 UTC
### Expected behavior
When updating an existing characterization with additional feature analyses, should be able to save changes and generate on data sources. 

### Actual behavior
When updating an existing characterization with additional feature analyses, cannot save changes or generate on data sources.
### Steps to reproduce behavior
Using epibeta.jnj.com characterization #27 add feature analyses - demographics age group, age etc; click save button. Please see attached error pages. 
![characterizationerror](https://user-images.githubusercontent.com/11822115/52080003-ce52c900-2564-11e9-8be0-234683760489.jpg)
![characterizationerror1](https://user-images.githubusercontent.com/11822115/52080005-ce52c900-2564-11e9-8da9-35523e281f29.jpg)

**Comment by aklochkova** [comment] 2019-02-04 12:23
@jhardin29 Hello! Could you please attach this characterization here?
And please describe permissions which do you have for this characterization.
I cannot reproduce this behaviour: if I have 'generate' and 'put' permissions everything is saved ok and Generate button is enabled.

**Comment by pavgra** [comment] 2019-02-14 14:05
@anthonysena , would it be possible to check the presence of the issue using the latest codebase?

**Comment by anthonysena** [comment] 2019-02-14 14:20
I'm unable to reproduce this bug on the latest code base - I'm going to close this out but @jhardin29 please re-open this if the issue persists. Thanks!

**Closed by anthonysena** 2019-02-14 14:20 UTC
Labels: bug, cohort characterization
