### ISSUE TITLE
Tight coupling between search and concept sets

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1493] opened 2019-03-12 16:11 UTC
### Enhancement request
When selecting a user created concept set to include in a characterization in the feature analysis section it would be useful to be able to view the concept set.  Flagging @anthonysena since we IMed about this issue.

**Comment by AntonStepanof** [comment] 2019-04-04 08:40
@jhardin29 @anthonysena Should it be additional column Concept Set in Feature analyses table? 
I guess, it can be column 'Concept Set' after 'Actions'. If there is a Concept Set for specific analysis, it will be clickable name of Concept Set(with routing to Concept Set view). Is it correct?

**Comment by chrisknoll** [comment] 2019-04-04 14:12
@jhardin29 : doesn't the criteria editor let you view the selected concept set by using the drop-down 'concept set quickview'?   But this doesn't really let you modify the concept set by adding/removing concepts.  Nor can you see a list of all concept sets in a feature analysis so you can get rid of unused concept sets.

Hi, @AntonStepanof,
  In a given feature analysis 'set' there are multiple concept sets that could be used across the series of criteria features.

I'd suggest we handle this like we do with concept sets attached to cohort definitions, or concept sets attached to incidence rate analysis.  

Cohort definition:
![image](https://user-images.githubusercontent.com/6818777/55561693-9da42280-56c0-11e9-9965-7c9ccf2fc26c.png)

The limitation here is:  adding/removing concept sets is done at a 'global' level (in Model.js).  Wen you pick a concept set to edit, it puts it into a 'global' variable where you go through the vocabulary search UI to add/remove concepts.

Incidence Rates:  where we edit the concept set locally in the incidence rate:

![image](https://user-images.githubusercontent.com/6818777/55562064-3c308380-56c1-11e9-8ba4-aaa79213e80d.png)

Vocabulary searching is using a very simplified ui:
![image](https://user-images.githubusercontent.com/6818777/55562086-481c4580-56c1-11e9-9f40-843d36f47964.png)

What we should have is a completely encapsulated search component that lets you search, navigate to concept hiearchy/ related concepts, and then select conepts to add to the 'target' concept set expression.  Could be simply adding a tab to the concept set editor:

![image](https://user-images.githubusercontent.com/6818777/55562352-bfea7000-56c1-11e9-80c3-f3e8b2637eb0.png)

Under the search tab, you have the ability to search the vocab, navigate between concepts, and then finally select the concepts you want to add into the concept set.  In fact, the 'Included Concepts' and 'Included Source Codes' should behave the same way: you select concepts you want to add to the concept set expression, and then decide to 'add as exclusions/add with descendannts' etc.

Today, with the 'shopping cart' pattern, you can only have 1 concept set open at a time, forcing you to close a cohort definition before working on a concept set.  It also leads to tons of complexity in Model.js (which we want to clean up in #1565).  We should get rid of shopping carts, and instead give the user an option to 'select' concepts to 'include/exclude' and this selection could come from either search results, related concepts, or the included concepts view.

**Comment by AntonStepanof** [comment] 2019-04-09 09:06
@chrisknoll For criteria editor it is possible to choose specific concept set:
![cs1](https://user-images.githubusercontent.com/48437569/55787484-09bac800-5abf-11e9-91d7-3577648b5b71.png)
For this problem should we add concept set only for Custom Feature type?
Also for this screen currently we don't use tab-panel, like in cohort definitions or incidence rate analysis. Should I introduce it here?

**Comment by chrisknoll** [comment] 2019-04-09 13:06
@AntonStepanof : I think you are showing the concept sets that you can import from the 'concept set repository'.  yes, you can import from the repository, but there's no way to view the list of imported concept sets and then edit/remove them.

> For this problem should we add concept set only for Custom Feature type? (I just realized 'custom feature' in the issue title, when I meant to say 'criteria feature'. I will update the title.)

The 'preset features' and 'custom features' don't reference anything by concept set.  The issue is the users can not see all the concept sets that have been imported into the Criteria Feature analysis, and they can't edit/update the existing concept set.

> Also for this screen currently we don't use tab-panel, like in cohort definitions or incidence rate analysis. Should I introduce it here?

Yes.  However, there's a deeper issue which is there is a tight-coupling between the search experience (the shopping charts) and the concept set editor within 'cohort definitions' and 'concept set repository'.  It's so tight that you actually have to _close the cohort definition before editing the concept set from the repository!_.  Part of this effort should be to extract the vocabulary search experience (which includes:  search by text, advanced search options, viewing the concept details/related concepts/concept hierarchy).  Once that is extracted, we can embed 'vocabulary searching' wherever we have a concept set to edit (incidence rates, cohort definitions, estimation, prediction, concept set repository) and allow users to 'add concepts' to the concept set expression via a local vocabulary search.

This involves a major un-tangling of code in Model.js that has a lot of logic in it to ensure that you only have 1 concept set open at a time and has a lot of logic to keep track of where the opened concept set came from (which is either an open cohort definition or an open concept set from the repository).

I would strongly urge us to open up a new 'search redesign' issue for Atlas, and completely plan out how we want the function to work before diving in and making changes only to Criteria Features.  If you think we can go in that direction, I can get the ball rolling with a new issue, and produce screen mockups and detail some of the functional requirements.

**Comment by AntonStepanof** [comment] 2019-05-07 08:25
@pavgra Could you please check this problem? Looks like it should be fixed as part of 'search redesign' . Please check previous comment from Chris

**Comment by pavgra** [comment] 2019-07-25 17:10
@pbr6cornell , this issue seems like a duplicate of https://github.com/OHDSI/Atlas/issues/1595. Could you confirm and close this one if you agree?

**Comment by olga-ganina** [comment] 2019-11-29 12:28
Hi @anthonysena , can you please assist with closing as duplicate if that's ok?

**Comment by anthonysena** [comment] 2019-12-17 14:09
Renaming this issue and moving it to Atlas 3.0 since this thread has a lot of good discussion related to how search & concept set management is done in 2.x and should be refactored for 3.0.

**Comment by chrisknoll** [comment] 2020-09-21 05:13
We've introduced consistent concept selection for any/all design entities in atlas 2.8.

**Closed by chrisknoll** 2020-09-21 05:13 UTC
Labels: cohort characterization, enhancement
