### ISSUE TITLE
Can't see Included Concepts in the table of Concept Sets

### ISSUE THREAD

**Issue by anemniugin** [OHDSI/Atlas#1518] opened 2019-03-15 14:48 UTC
### Expected behavior
Can see  included concepts

### Actual behavior
Empty table

### Steps to reproduce behavior
Login
Go to Concept Sets
Create new Concept Set
Go to Search
Search "aspirin"
Add one or more Aspirin to cart
Go to concept set by link at the top of the table
Open Included Concept tab(with digit)

if you set checkbox e.g. Descendants, and set it off, you can see correct rows in Included Concepts tab,

**Comment by anthonysena** [comment] 2019-03-18 17:15
Looking into this a bit more, I'm finding that the trouble related to this issue stems from the way that we attempt to load up included concepts. Here is the code:

https://github.com/OHDSI/Atlas/blob/v2.7.0-rc/js/Model.js#L779

```
loadIncluded(identifiers) {
	this.loadingIncluded(true);
	const data = identifiers || this.conceptSetInclusionIdentifiers();
```

It is assumed that the `identifiers` for the concept set (i.e. the list of concepts that are resolved from the concept set expression) are passed into this function to look up the identifiers. When `identifiers` are not passed into the function, it will attempt to use `this.conceptSetInclusionIdentifiers()` which is set when calling the resolveConceptSetExpressionSimple function:

https://github.com/OHDSI/Atlas/blob/v2.7.0-rc/js/Model.js#L399

In the scenario described in this issue, the problem lies in the fact that the concept set has yet to be saved and as a result, both the `identifiers` and `this.conceptSetInclusionIdentifiers()` are not specified therefore returning 0 included concepts. 

The approaches that both @pavgra and I put into #1546 simply adds more calls to `resolveConceptSet` to work around the root cause of this issue. Instead of applying this work around which then causes needless calls to the same REST endpoints, we should examine the way in which we are resolving a concept set to find the included concepts & source codes. This should be uniformly applied regardless of if the concept set is new or saved.

**Closed** 2019-04-03 12:49 UTC
Labels: bug, vocab/conceptset
