### ISSUE TITLE
Add description field to ConceptSet

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#2204] opened 2020-05-07 01:06 UTC
### Expected behavior
I can describe concept set

### Actual behavior
no place to say who created it (if on covid server), put references, write notes (like for cohorts)

### Steps to reproduce behavior
n/a

**Comment by gklebanov** [comment] 2020-05-07 01:18
Yes, agreed. I would broaden this request because I think we need to be very consistent across all artifacts
- author
- created data
- modified date
- modified by
- title
- description

also, these attributes should be displayed on a main screen as well.

**Comment by anthonysena** [comment] 2022-05-03 22:14
Closing as it is a duplicate of #1823

**Closed by anthonysena** 2022-05-03 22:14 UTC
