### ISSUE TITLE
concept set compare venn diagram tooltip needs style update

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#2824] opened 2023-01-31 18:12 UTC
### Expected behavior
legible tooltips

### Actual behavior
generally difficult to read given current colors

### Steps to reproduce behavior
view venn diagram from the concept set comparison screen.

![image](https://user-images.githubusercontent.com/6586384/215847072-f61bb6f5-70e3-444e-bac4-7c6d3ddd5ead.png)

**Comment by anthonysena** [comment] 2024-11-08 21:57
This appears to be fixed (or working as intended) using the latest version of ATLAS in Chrome. See below. I'm going to close this out but if you find it is still an issue please re-open and let us know.

![image](https://github.com/user-attachments/assets/2bb1becb-1b4e-4704-9391-623c03d4418d)

**Closed by anthonysena** 2024-11-08 21:57 UTC
Labels: bug
