### ISSUE TITLE
Text input from right to left

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#422] opened 2017-07-18 20:39 UTC
### Expected behavior
Choose any cohort . Go to tab 'Concept Sets' - 'New Concept Set'
Enter name of New concept Set. 
Text should be written left to right
### Actual behavior
Text is written right to left

**Comment by chrisknoll** [comment] 2017-07-18 20:40
Dupe of #384

**Closed by chrisknoll** 2017-07-18 20:40 UTC
