### ISSUE TITLE
searching units that include "/"

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/Atlas#386] opened 2017-03-29 22:54 UTC
### Expected behavior
Search "mg/L" with or without quotations should return results. 

### Actual behavior
Search page hangs at 
http://hix.jnj.com/atlas/#/search/mg/L
or
http://hix.jnj.com/atlas/#/search/%22mg/L%22

### Steps to reproduce behavior
Search "mg/L" with our without quotations

**Comment by fdefalco** [comment] 2017-12-28 18:25
dupe of #119

**Closed by fdefalco** 2017-12-28 18:25 UTC
Labels: bug, system, vocab/conceptset
