### ISSUE TITLE
Cohort Characterization failures

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1137] opened 2018-11-16 18:02 UTC
### Steps to reproduce behavior
generating a cohort characterization fails in many datasets
![image](https://user-images.githubusercontent.com/19151846/48638820-bb861a80-e99f-11e8-94fa-ccce5c0cd5cd.png)

**Comment by anthonysena** [comment] 2018-11-16 20:09
@jswerdel - can you share the details around what characterizations in our environment exhibit this behavior? Having an ID for the failing characterization and note about the environment (beta/prod) will help us track this down. Thanks!

**Comment by anthonysena** [comment] 2019-02-11 19:57
@jswerdel - I'm closing this out as I don't have the details for this issue. If you have a characterization that is consistently failing, please post the cohort characterization design (JSON export) and we can review it. Thanks!

**Comment by SelvaSathappan** [comment] 2019-04-23 07:58
Hello @anthonysena - We are facing similar issue. Our Cohort Characterization generation are failing, Can you please let us know what can be the reason?

I have attached the JSON code generated from Utilities section. Can you let me know how can we generate cohort characteristics without any error?

[JSON_COHORT_Characterization.pdf](https://github.com/OHDSI/Atlas/files/3106453/JSON_COHORT_Characterization.pdf)

**Comment by anthonysena** [comment] 2019-04-23 16:57
Hi @SelvaSathappan - thanks for sharing these designs. In the future, it might be easier to transfer these as plain text vs. PDFs (otherwise I have to copy/paste and edit).

I loaded these into our environment and before attempting to run the characterization, I generated the cohorts to ensure that they contain people. For both designs, these cohorts return 0 people due to the inclusion rule which requires a diagnosis of Hypocholestromia in and around the drug exposure. This could be part of the issue your facing here.

Also worth noting: using the latest Atlas/WebAPI code-base, I was able to generate the characterization without issue and it appears to properly handle the case when a cohort in the characterization design contains 0 people. Since I'm unable to reproduce this issue, I'm going to close this out and would recommend that you investigate the cohort design and consider upgrading to the latest code base.

**Closed by anthonysena** 2019-04-23 16:57 UTC
Labels: bug, cohort characterization

**Comment by SelvaSathappan** [comment] 2019-04-23 23:18
Hello @anthonysena ,

I have attached another json file export for paracetamol cohort. These cohort returns records. However, the characterization is still failing. Can you please look into this and let us know whether everything is right?

![T1](https://user-images.githubusercontent.com/30723825/56622008-b87f0c80-6658-11e9-975b-a330ceba713b.JPG)

[PARACETAMOL_CHARACTERIZATION.txt](https://github.com/OHDSI/Atlas/files/3109919/PARACETAMOL_CHARACTERIZATION.txt)

**Comment by SelvaSathappan** [comment] 2019-04-24 08:13
Hello @anthonysena ,

In addition, after upgrading to the latest version, I see that the cohot characterization is still failing. When I clicked on the "failed" status, I was able to see an error message/exception which I have attached for your reference. Can you please help us understand what is the issue?

[error_failed_characterization.txt](https://github.com/OHDSI/Atlas/files/3111240/error_failed_characterization.txt)

**Comment by anthonysena** [comment] 2019-04-24 12:31
Hi @SelvaSathappan 

Looking at the error, it appears you are missing a table:

`nested exception is org.postgresql.util.PSQLException: ERROR: relation "public.cc_results" does not exist`

Please refer to this section on setting up your results schema:

https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#results-schema-setup

Using the URL described in that section, you should be able to retrieve all of the required tables for your results schema, including the `cc_results` table. Hope this helps!
