### ISSUE TITLE
Unable to save concept set made in cohort to the concept set repository

### ISSUE THREAD

**Issue by llhester** [OHDSI/Atlas#1075] opened 2018-10-29 18:42 UTC
### Expected behavior
When you create a concept set within a cohort definition, it is expected that the "Copy to Concept Set Repository" button will copy to the Concept Set repository with all of the concepts included/excluded.

### Actual behavior
Although the concept set is created with the designated name in the concept set repository, none of the included/excluded concepts are being copied over. The result is an empty concept set.

### Steps to reproduce behavior
1) Created a concept set within a cohort definition
2) Selected the  "Copy to Concept Set Repository" button 
3) Went to the concept set repository,  where the the concept set was created with *no* concepts.

**Comment by anthonysena** [comment] 2018-10-30 02:57
Thanks for reporting this @llhester. I'm going to close this since it is a duplicate of #1036 but you are the 3rd person from our team to report it so we'll prioritize getting a fix for this one.

**Closed by anthonysena** 2018-10-30 02:57 UTC
Labels: bug, vocab/conceptset

**Comment by llhester** [comment] 2018-10-30 02:59
Sorry Anthony! I really did look through them, but I guess I missed that one.
