### ISSUE TITLE
Cohort names not unique

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#1638] opened 2019-04-02 16:45 UTC
### Expected Result

When creating a cohort name, only unique names should be allowed

### Actual Result

ATLAS allows the user to create cohorts with the same exact name but different number

### Steps to reproduce

Create two cohorts, and then give them the same name

**Comment by pavgra** [comment] 2019-04-09 13:17
Duplicate of https://github.com/OHDSI/Atlas/issues/1338

**Closed by pavgra** 2019-04-09 13:17 UTC
Labels: bug, cohort
