### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Atlas#502] opened 2017-11-09 01:36 UTC
### Expected behavior
I select standard concepts from the same domain, name the concept set, then save the concept set without getting an error.
### Actual behavior
I do the above and receive this error:
<img width="449" alt="screen shot 2017-11-08 at 6 03 48 pm" src="https://user-images.githubusercontent.com/22457958/32583915-08b5522a-c4b3-11e7-9a00-723b33b26937.png">
I do not see the "configuration button in the top right hand corner". 
### Steps to reproduce behavior
Try to make a concept set from these concepts:
<img width="1056" alt="screen shot 2017-11-08 at 6 33 36 pm" src="https://user-images.githubusercontent.com/22457958/32584043-bb2f098c-c4b3-11e7-8af9-1adf8ebfd9d4.png">

**Comment by anthonysena** [comment] 2017-11-10 16:46
Hi @MelaniePhilofsky - I'm unable to reproduce the issue on my side. I've created the same concept set here for reference:

http://www.ohdsi.org/web/atlas/#/conceptset/1248821/details

I investigated the error message and that particular message appears to happen when attempting to see if a concept set with the same name already exists in the system. Does your concept set name contain any special characters like "/" or "&"? As a note to myself: the error message should be changed to something more informative.

**Comment by jhardin29** [comment] 2017-11-10 16:54
Hi @anthonysena and @MelaniePhilofsky I have a feeling I know the issue - if you use non alphanumeric characters to name your concept set the error appears that was posted. For example using "/" has been problematic for me and resulted in the same error that was originally posted.

**Comment by MelaniePhilofsky** [comment] 2017-11-10 20:08
Thank you @anthonysena and @jhardin29 ,

I do think I used the special character "/" when naming my concept set. A more descriptive error message would be helpful. Would allowing special characters be feasible?

**Comment by anthonysena** [comment] 2017-11-10 21:42
Hey @MelaniePhilofsky and @jhardin29 - yes, this was a bug due to the special characters. I've submitted a fix for this and it should be part of a 2.2.1 build of Atlas/WebAPI.

**Comment by jhardin29** [comment] 2017-11-10 23:39
Thanks! @anthonysena

**Closed** 2017-11-13 16:20 UTC
