### ISSUE TITLE
Unable to create concept set when concepts are imported

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#40] opened 2016-03-15 15:01 UTC
After importing a new concept set on the import tab, the entire concept set is selected but does not create a new concept set. For now I've worked around it by first clicking on new concept set, and then importing the set afterwards

**Comment by anthonysena** [comment] 2016-03-18 13:20
Steps to reproduce: make sure no concept set is active, go to vocab search, select import, paste in a concept set definition. The definition will appear after import but will not be associated to a default concept set.

**Comment by anthonysena** [comment] 2016-03-24 19:51
Rupa, we're going to move the import concept set functionality to a new tab on the concept set page. This should make the process importing a concept set cleaner and should eliminate this issue.

**Comment by chrisknoll** [comment] 2016-03-25 16:23
I'm going to do a little refactoring for this issue:  we currently have a copy of the concept set editor (with tabs) in different places because of slightly different user experience requiremeents (for example, when editing in a cohort, we have a name label, when in a concept set, it's in the header.)  But I think this can be standardized into a single component, with 'decorations' for the name label and 'delete/close' buttons surrounding the main content.  This will allow us to make fixes in 1 place instead of finding the different locations.

**Comment by chrisknoll** [comment] 2016-03-25 19:21
On second thought, maybe not.  The routing is baked into each of these places, and so without additional redesign, I can't make this work. I think we need to evaluate how routes are being fired in our components, because that's locking them into a one-component-one-use scenerio, and that'll lead us to a lot of copy-paste of our components just because of a different route behavior.

**Comment by chrisknoll** [comment] 2016-03-25 20:05
Fixed this to create a new concept set during import.  Moving the tab out of search was not necessary.

Fixed in commit 9f57554e1de42a20cc68d17657b76dcdf3cb7225.

**Closed by chrisknoll** 2016-03-25 20:05 UTC
