### ISSUE TITLE
Error message after copying a cohort where the cohort copy does not happen

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1531] opened 2019-03-15 20:21 UTC
### Expected behavior
The cohort gets copied after hitting the 
![image](https://user-images.githubusercontent.com/19151846/54459827-312ba880-473e-11e9-97a5-ebb2f08dd89b.png) button

### Actual behavior
The following error message appeared:
![image](https://user-images.githubusercontent.com/19151846/54459856-40aaf180-473e-11e9-80c1-23d0f5106fca.png)

### Steps to reproduce behavior
I've never seen this happen before but it may have occurred during a period of high cohort creation volume.

**Comment by ssuvorov-fls** [comment] 2019-04-04 09:12
@jswerdel 
Did this error message appear in console?
Dit it appear before or after page reload?

**Comment by pavgra** [comment] 2019-04-05 15:22
@anthonysena , could you try to reproduce this issue in your env? we cannot achieve the same result

**Comment by anthonysena** [comment] 2019-04-05 15:42
I'm unable to reproduce this - it could be that there was a different problem in our environment that caused it. I'll close this now but @jswerdel please let us know if you encounter this again.

**Closed by anthonysena** 2019-04-05 15:42 UTC
Labels: bug, cohort
