### ISSUE TITLE
Prediction study: Random forest input type error for varImp

### ISSUE THREAD

**Issue by jreps** [OHDSI/Atlas#1168] opened 2018-11-27 22:13 UTC
### Expected behavior
The input for the varImp variable in the random forest model should be either: i) true or ii) false or iii) true,false  and then this should create a vector in the json settings: i) [true] or ii) [false] or iii) [true,false]
### Actual behavior
it creates a string in the json settings i) "true" or ii)'false" or iii) 'true,false'

This causes an error when running the atlas created plp package

**Comment by mpozhidaeva** [comment] 2019-02-07 13:51
@anthonysena - I can't find the use of the RandomForestSettings class in the WebAPI. 
Could you please clarify the purpose of this class, or can I delete it?

**Comment by pavgra** [comment] 2019-02-15 20:01
Talked to @anthonysena and we've decided that the issue is going to be resolved in a more human-friendly way by enabling multi-select component (with preset options for this concrete field - true/false). He is going to apply such multi-select component to support settings permutations in multiple places (settings)

Smth like:
```
<multi-select-list params="type: 'options', options: [{label: 'True', value: true}, {label: 'False', value: false}], ..." />
<multi-select-list params="type: 'integer', ..." />
...
```

![image](https://user-images.githubusercontent.com/10010071/52881428-8326e180-3132-11e9-8541-b89f1c03ff28.png)

**Closed** 2019-02-28 21:14 UTC
Labels: bug, plp
