### ISSUE TITLE
[ATLAS 2.7 TEST] Copy of comparison removes cohorts 

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#1576] opened 2019-03-20 19:37 UTC
### Expected behavior
When copying a comparison in the estimation editor the T, C, O, and negative controls remain the same.

### Actual behavior
The T and C cohorts are removed (see below)
![image](https://user-images.githubusercontent.com/12911960/54713958-3e71da00-4b26-11e9-8e9e-e13ef404ec56.png)

### Steps to reproduce behavior
Copy a comparison

**Comment by anthonysena** [comment] 2019-04-02 19:35
Hi @clairblacketer - this behavior is by design with the thinking: when copying a comparison, you'll likely want to define a new T & C to use in your comparison but keep the same outcomes & negative controls. I can see where it may be confusing since you state you'd like a copy and expect it to give you an exact copy vs. a partial copy. I'm going to close this out but we can revisit if others in the community also find this behavior confusing.

**Closed by anthonysena** 2019-04-02 19:35 UTC
