### ISSUE TITLE
User unable to sign-in against Active Directory after some time

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Atlas#1183] opened 2018-12-05 19:56 UTC
### Expected behavior

After successfully signing in against Active Directory and using Atlas, at any time later time (e.g. after time out), user is able to sign-in with the same correct credentials.

### Actual behavior

After successfully signing in against Active Directory and using Atlas, at some later time (presumably after time out), **user is unable to sign-in with correct credentials**. System shows error message `bad credentials.`

### Steps to reproduce behavior

1. User signs in using Active Directory credentials.
2. User uses Atlas.
3. User comes back to browser session to find sign in screen.
4. User is unable to sign-in with correct credentials. System shows error message `bad credentials`.

**Comment by t-abdul-basser** [comment] 2018-12-05 20:03
### Additional information

This is an issue that several users have experienced department-wide production deployments here at Columbia University. 

Version: Atlas 2.5.x
Security mechanism: Windows Active Directory

### Possible workaround

A hard refresh in Chrome allow users to sign in.  Browser refresh does not work.

**Comment by AntonStepanof** [comment] 2019-06-03 10:08
Cannot reproduce locally. Created pr with additional logging during failed login - https://github.com/OHDSI/WebAPI/pull/1164

**Comment by olga-ganina** [comment] 2020-01-16 11:11
Hi @t-abdul-basser , do you still have this issue on latest Atlas version? We cannot reproduce it on our side, unfortunately.

**Comment by olga-ganina** [comment] 2020-07-21 11:12
Confirmed with @anthonysena  that we can close this one because we cannot reproduce initial problem and no additional information is received.

**Closed by olga-ganina** 2020-07-21 11:12 UTC
Labels: bug, system, work-around
