### ISSUE TITLE
Vocabulary switching 

### ISSUE THREAD

**Issue by denyskaduk** [OHDSI/Atlas#2223] opened 2020-05-29 12:52 UTC
### Expected behavior
When switch from default vocabulary to vocabulary with custom concepts and create Concept Set based on custom concepts. After saving Concept Set and reopening it, should not return to default.

### Actual behavior
When switch from default vocabulary to vocabulary with custom concepts and create Concept Set based on custom concepts. After saving Concept Set and reopening it, custom concepts disappeared and vocabulary switched back to default.

### Steps to reproduce behavior
Configuration  
![Vocab1](https://user-images.githubusercontent.com/42732735/83261285-c1c79a80-a1c3-11ea-9543-8a75192a635f.PNG)

Switch to Vocab with custom concepts (or concepts which not present in default Vocab)
![Vocab2](https://user-images.githubusercontent.com/42732735/83261349-defc6900-a1c3-11ea-906a-b0d32db6d91a.PNG)

Create Concept Set with concept which not in default vocabulary
![ConcepSet1](https://user-images.githubusercontent.com/42732735/83261457-06533600-a1c4-11ea-807c-4ecb46ccf69c.PNG)

Save, close  and reopen it
![ConceptSet2](https://user-images.githubusercontent.com/42732735/83261503-1ff47d80-a1c4-11ea-809b-ac9261722f7d.PNG)

See that they disappeared and vocabulary switched to default

**Comment by olga-ganina** [comment] 2020-05-29 16:01
@YaroslavTir please take this fix from 2.8

**Comment by YaroslavTir** [comment] 2020-06-09 09:53
fixed by these PRs:
https://github.com/OHDSI/Atlas/pull/2228
https://github.com/OHDSI/WebAPI/pull/1552

**Comment by YaroslavTir** [comment] 2020-06-16 12:22
the issue is still reproducible in case of a refreshing page. 
I wrote a possible solution to store default-datasources for the current session in localStorage: https://github.com/OHDSI/Atlas/tree/issue-2223-local-storage
the following things need to be clarified:
* when should we reset default data set (now that is login)
* I noticed that toggle between application/session mode does not affect the configuration page. I think that `Version/Evidence/Record Counts` should change as well

**Comment by aklochkova** [comment] 2020-07-03 15:29
This PR (https://github.com/OHDSI/Atlas/pull/2241) fixes only the case about page refresh.

The following points which @YaroslavTir mentioned above are needed to be discussed:
1) end of a session:
    1. now 'Current session' settings are reset on successful login
    2. what should happen if the user closes and then reopens a browser
    3. what should happen if a session expires on a server
2) what should happen after the following steps:
    1. user chooses some settings in 'Current settings' mode
    2. then user switches to 'Whole application' mode and chooses other settings
    3. then user switches back to 'Current settings'

Should the settings from p.1 be restored?

Also, it might be convenient to display what vocabulary is currently in use when switching to other tabs, i.g. display the vocabulary name on the 'Search' tab.

**Closed** 2020-07-30 08:13 UTC
Labels: June16-June30, June30-July13, bug

**Comment by aklochkova** [comment] 2020-07-31 09:41
Should be verified for v.2.8.
