### ISSUE TITLE
Characterization plots not displayed correctly

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1143] opened 2018-11-16 21:02 UTC
### Expected behavior
When comparing cohorts in characterization the standardized difference plots will display upon page entry; also page is unable to scroll without lag
### Actual behavior
Standardized difference plots did not display until user clicked the page area where they should appear
### Steps to reproduce behavior
Go to characterization #58 CCAE results and review results

**Comment by vlbe** [comment] 2019-02-08 11:33
@jhardin29 Hello, can you reproduce this bug now? And if yes, please attach exported characterization.

**Comment by anthonysena** [comment] 2019-02-08 15:01
I'm going to close this for now since I'm having trouble reproducing this on the latest code. I think the trouble here is related to the amount of data returned, not the design of the characterization itself. I'm going to open another issue for 2.8 to make reference of this issue.

**Closed by anthonysena** 2019-02-08 15:01 UTC
Labels: bug, cohort characterization

**Comment by anthonysena** [comment] 2019-02-08 15:52
Tying to #1320
