### ISSUE TITLE
Not allowing save of  "continuous observation days before field" after first save

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#393] opened 2017-04-19 19:46 UTC
### Expected behavior
Changing the continuous observation days before in a cohort that was previously saved should trigger the Save button to turn green and allow a save

### Actual behavior
The change does not trigger the change in the save button.
Also if another field is changed at the same time, the save button will get triggered but hitting the save button will save all changes except for the  continuous observation days before which will revert to its former value (from the original save)
### Steps to reproduce behavior
1) go to a previously saved cohort and note the  continuous observation days before field value
2) change the  continuous observation days before field
   -- note that save button does not change to green
3) change any other field
   --note change in save button
4) click save button
   --note that  continuous observation days before field has reverted back to original value

**Comment by ericaVoss** [comment] 2017-04-19 19:51
I have seen this behavior as well.

**Comment by chrisknoll** [comment] 2017-04-20 04:08
Ok, this was a recent change that had to fixup a problem caused by a recent chrome update (I believe).  I had to change that text input fields a bit to workaround the behavior but here is what's happening:

I had to change the behavior of those input fields to store the value after you leave the field.  So, using the dropdown selection should cause an immediate update, but just typing into the field doesn't actually trigger any update until you leave the field.  Immediately clicking on the save button is where it gets interesting:  the save button acts before the 'leave field' acts, so the save is made first, then the field updates but you don't see anything because the save gets the latest version of the cohort definition from the save call and overwrites the UI with the saved value (which is the value of the input box the instant before the update could be applied into the model).

So, the fix is that I need to defer the save click action from happening until all the UI fields finish populating their data into the model.  So, let me work out how this should operate and I'll push up a fix.

Sorry for the confusion on this!

-Chris

**Comment by alondhe** [comment] 2017-05-17 03:19
So I'm seeing something similar, but for any day range dropdown (initial event inclusion criteria or additional qualifying inclusion criteria). The Save button does become enabled, but the changes do not persist.

**Comment by chrisknoll** [comment] 2017-05-18 14:46
@jswerdel , @jreps, @pbr6cornell , @alondhe , @ericaVoss :

Tagging you all since you have been bit by this issue in one area of the app or another.  I've pushed to our local environment something that should account for all the cases described above (and some others not), so could you please try on our internal environment and report any issues?  I'll also follow up with you directly.

Long story short: there's two things competing for those numeric fields:  an auto-complete a numeric format validator (which requires the value to be parsed only after the field is blurred, otherwise it will reset the value when you start typing in a number like '-5' (- is not a number).  Plus, chrome had an update recently that seems to propagate events , in a different order, which invalidated a few assumptions that were in the code.  All of this beign said: I hope I have something that will robustly handle the various sources of updates.  Only thing to remember is that the field will not update the model until the field is 'blurred' or left focus, so use tab to move off the filed if you are confused why the save indicator appears to not 'see' your changes.

**Comment by anthonysena** [comment] 2017-07-20 16:03
I believe this has been resolved with #403. @chrisknoll please re-open if I'm mistaken here.

**Closed by anthonysena** 2017-07-20 16:03 UTC
Labels: bug, cohort
