### ISSUE TITLE
ATLAS Version 2.0.0 Data Sensity report issue with PostgreSQL

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Atlas#389] opened 2017-04-10 21:33 UTC
### Expected behavior

On Data Sources, select Data Density report - report should appear

### Actual behavior

UI displays error loading report

### Steps to reproduce behavior

On Data Sources, select Data Density report

When looking at this issue more closely, I am seeing my catalina.log file that Atlas is running the following query:

<code>
SELECT
  t1.table_name                                      AS "series_Name",
  t1.stratum_1                                       AS "x_Calendar_Month",
  ROUND(CAST(1.0 * t1.count_value / denom.count_value AS NUMERIC), 5) AS "y_Record_Count"
FROM
  (
    SELECT
      'Visit occurrence' AS table_name,
      stratum_1,
      count_value
    FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 220
    UNION ALL
SELECT
  'Condition occurrence' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 420
UNION ALL
SELECT
  'Death' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 502
UNION ALL
SELECT
  'Procedure occurrence' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 620
UNION ALL
SELECT
  'Drug exposure' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 720
UNION ALL
SELECT
  'Observation' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 820
UNION ALL
SELECT
  'Drug era' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 920
UNION ALL
SELECT
  'Condition era' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 1020
UNION ALL
SELECT
  'Observation period' AS table_name,
  stratum_1,
  count_value
FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 111
) t1
INNER JOIN
( SELECT * FROM rs_schema_stride6_strict_vj.ACHILLES_results WHERE analysis_id = 117) denom
ON t1.stratum_1 = denom.stratum_1
ORDER BY SERIES_NAME, CAST(t1.stratum_1 AS INT )
</code>

When I run this directly I get the following error:
<code>
ERROR:  column "series_name" does not exist
LINE 64: ORDER BY SERIES_NAME, CAST(t1.stratum_1 AS INT )
                  ^
********** Error **********

ERROR: column "series_name" does not exist
SQL state: 42703
Character: 1786
</code>

The easy fix is to change SERIES_NAME to t1.table_name, this allows the query to run properly

**Comment by mark-velez** [comment] 2017-05-05 16:31
@jmbanda thank you for the detailed report. This is a duplicate of OHDSI/WebAPI#183 which should now be resolved. If you see this again, please submit an issue in the WebAPI repo.

**Closed by mark-velez** 2017-05-05 16:31 UTC
