### ISSUE TITLE
Length of comment in enter inclusion rule description box caused cohort to fail generating

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#737] opened 2018-06-07 20:03 UTC
### Expected behavior
if the length of the text entered in the inclusion rule description box exceeds the allowable number of characters and spaces an error is raised to the user so they can delete characters and spaces
### Actual behavior
After entering text and spaces of at least 1223 characters in an inclusion rule description box and clicking the generate button the cohort fails to generate
### Steps to reproduce behavior
enter text and spaces of at least 1223 characters in the inclusion rule description box and click the generate button

**Comment by aklochkova** [comment] 2019-02-08 11:05
@jhardin29 Hello, I can't reproduce this bug. Could you please re-check if it is actual in the latest master?

**Comment by anthonysena** [comment] 2019-02-11 18:50
@aklochkova - I'm unable to reproduce this on the latest code so I'll close this out. Thanks!

**Closed by anthonysena** 2019-02-11 18:50 UTC
Labels: bug, cohort
