### ISSUE TITLE
Profiles nav resets IR analysis to new instance.

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/Atlas#1509] opened 2019-03-14 12:45 UTC
### Steps to reproduce behavior

1. Open any IR
1. Close the IR
1. Observe that IR icon in the menu is green
1. Go to 'Profiles' tab

### Expected behavior
IR icon is white, not green, in step 3

### Actual behavior
IR icon is green on the left pane in step 3. And if you go to IR tab the list of all IR's is expected but IR from step 1 is opened

**Comment by chrisknoll** [comment] 2019-03-14 13:15
@aklochkova ,
 I cant' reproduce this, but your actual behavior describes the proper result:

> Open any IR
The icon turns green indicated you have an open, no-changes to save IR.

> Close it and observe that icon on the left pane is white not green
Yes, you now have closed the IR, so it is no longer open, so the icon is no longer green.

> Go to 'Profiles' tab
Icon is still whilte (no IR open)

Then I clicked back on the IR left-nav, and got the IR list.  The previous open IR was not open.

Do I have your steps to reproduce correct?  I could be missing a step.

**Comment by aklochkova** [comment] 2019-03-14 13:44
@chrisknoll What I listed in "Steps to reproduce behavior" is correct behavior. 
You have reproduced all steps, yes. @vlbe caught a bug too

**Comment by chrisknoll** [comment] 2019-03-14 14:33
I'm still not clear on what the bug is. Everything you described is the correct behavior.  

What is the bug?

**Comment by aklochkova** [comment] 2019-03-14 14:40
@chrisknoll 

> Icon is still whilte (no IR open)
now it is green which is wrong

**Comment by chrisknoll** [comment] 2019-03-14 14:43
if you mean 'now' as in 'after closing the IR', then yes, closing the IR should return the status icon to white. If it says green after closing, then it's a bug.  If it stays green just switching to another nav (like Profiles), then it is NOT a bug. The IR instance remains open (sort of in the background) until you explicitly close it.  If you click to another nav (like profiles) with an IR open, and then click back to IR (with the green icon), you will return to the opened IR.  

I'll try to reproduce your issue by seeing if I can see a green icon in the left nav after closing the IR.

**Comment by pavgra** [comment] 2019-03-14 14:46
@chrisknoll ,
- I've updated the issue description. Hopefully, it clarifies things
- I believe the fix itself will contain ten times less code than your messages here...
- If we need help, we'll ask for, thanks

**Comment by chrisknoll** [comment] 2019-03-14 14:52
Ok, i think i see a bug:

Step 1: just starting from home screen:
![image](https://user-images.githubusercontent.com/6818777/54366161-8c7a6f80-4646-11e9-8a3f-854afc114137.png)

Step 2: get an IR list:
![image](https://user-images.githubusercontent.com/6818777/54366176-943a1400-4646-11e9-88b9-73b6336ab574.png)

Step 3: Open one (note icon goes green):
![image](https://user-images.githubusercontent.com/6818777/54366264-bb90e100-4646-11e9-89f6-2b92daf00ffa.png)

Step 4: navigate to profiles (Icon still green):
![image](https://user-images.githubusercontent.com/6818777/54366295-c9defd00-4646-11e9-87ce-237d03367786.png)

Step 5: look at the link URL for the IR:
![image](https://user-images.githubusercontent.com/6818777/54366437-06125d80-4647-11e9-8200-f658631e4d60.png)

So, while the icon is green (indicating there is an open IR), the URL path back to the IR analysis says /new.  That's a definite issue.  It should have been /iranalysis/35.

@pavel, I'm not sure that everyone is clear on what the actual issue is. So, while you want help only when asked for, please let me get clarity on what the actual issue is.  I'm not directing you in coding this, but I will continue to probe for information until I'm satisfied the actual issue is clear and what the resolution should be.

**Comment by aklochkova** [comment] 2019-03-14 15:01
@chrisknoll You forgot to close IR before going to 'Profiles' tab. Please watch this video: https://gyazo.com/7fcc241807771238940c05869f18b532
in the end IR tab icon should be white and I expected to see all IR's but not that one which I've already closed

**Comment by chrisknoll** [comment] 2019-03-14 15:09
Thanks for the video, that makes it clear, and I can see this issue on our own environment (the missing information for me was that closing the IR does reset the icon to white but I navigated to a different URL than profiles, and the IR icon stayed white). Just to be clear: the IR icon resets to green _only _ when navigating to profiles, not any of the other navs (cohort defs, home, search, etc).  So navigating to the Profiles module seems to reset the Incidence Analysis instance to a new instance.

Some additional information i noticed:

When starting fresh (via reload), going to the profiles nav does not trigger a 'new' IR analysis instance
Only after opening an IR analysis (regardless of if you close it or not), by navigating to the Profiles nav, you get a new instance of an IR Analysis put into scope.
Once you open an IR analysis, you will continue to get it 'reset' by clicking on the Profiles nav.  None of the other navs behave this way, navigating from IR analysis to Cohort Defs or Search keeps the IR analysis in scope, and you can navigate properly back to the IR analysis. So the left nav for the IR analysis URL is working properly, it's showing /new because the Profile nav seemed to overwrite the IR analysis session state with a blank IR.

Thanks for working with me on this, @aklochkova , I have a complete understanding now about the nature of the issue, and look forward to seeing the fix.

**Comment by chrisknoll** [comment] 2019-03-14 15:20
@aklochkova , did you want to modify the issue report to reflect that the issue isn't about some problem with the green icon (I believe the green icon is properly reflecting the state of the app:  that an IR analysis is instantiated).  I renamed the issue to reflect what I think we both agree is the underlying issue, but if you have corrections please make.

From your intial steps to reproduce, I'd put them int his order:

1. Open any IR
2. Close the IR {but this step is not actually necessary}
3. *Observe that the IR icon in menu is white after closing* {this is demonstrated in your video}
4. Go to 'Profiles' tab
5. Observe that IR icon in the menu is green
6. Navigate to IR analysis Nav, it shows 'new analysis'.  The Profiles tab somehow reset the IR analysis to an empty analysis (or reset the analysisId to 0)

**Closed** 2019-03-15 20:16 UTC
